### ISSUE TITLE
Warning: Package *Bloc-Serialization-STON depends on the following classes: BlElementCurrentProperties and BlElementStates

### ISSUE THREAD

**Issue by labordep** [OpenSmock/Bloc-Serialization#16]
Warning when loading the project:

Warning: Package *Bloc-Serialization-STON depends on the following classes:
  BlElementCurrentProperties
  BlElementStates
You must resolve these dependencies before you will be able to load these definitions: 
  BlElementCurrentProperties>>#stonProcessSubObjects:
  BlElementStates>>#stonProcessSubObjects:

When click on proceed, the project continue to load, at the end there are two missing classes:
- BlElementCurrentProperties
- BlElementStates

![image](https://github.com/OpenSmock/Bloc-Serialization/assets/49183340/7a4aaa35-00a1-437e-b734-dd3e716cba08)

**Comment by labordep** [comment]
@plantec, @tinchodias, did you remove `BlElementCurrentProperties` and `BlElementStates` from Bloc or this is a bug?
I'm a bit surprised because I couldn't find a commit for their removal :S

**Comment by tinchodias** [comment]
hello, it may be this: https://github.com/pharo-graphics/Bloc/pull/422

**Comment by labordep** [comment]
Thanks @tinchodias!

**Comment by tinchodias** [comment]
after the talk of Alain we realized this part of bloc was not used and (after asking Alain) we removed it with Cyril... some of it had been already kind of deactivated for months (states answering nil in blelement)

**Comment by labordep** [comment]
Yes no problem!
